const types = {
  GET_USERS: 'GET_USERS',
  GET_USERS_POSTS: 'GET_USERS_POSTS',
  GET_POST_DETAILS: 'GET_POST_DETAILS',
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
  SET_ACTIVE_POST: 'SET_ACTIVE_POST'
};

export default types;